FROM python:3.12-slim

WORKDIR /app

COPY ./docker/api/requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY ./models/model.joblib .
COPY ./src/api/main.py .

EXPOSE 8000
CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]