stages:
  prepare:
    cmd: python src/data/make_dataset.py
    deps:
    - data/raw
    - src/data/make_dataset.py
    outs:
    - data/preprocessed
  train:
    cmd: python src/models/train_model.py
    deps:
    - data/preprocessed
    - src/models/train_model.py
    outs:
    - models/trained_model.joblib
  evaluation:
    cmd: python src/models/evaluate_model.py
    deps:
    - models/trained_model.joblib
    - src/models/evaluate_model.py
    metrics:
    - metrics/accuracy.json:
        cache: false
