services:
  login-api:
    build: .
    ports:
      - "8000:80"
    environment:
      ISS: http://login-api:80
      DATABASE_CONNECTION: postgresql://login:login@login-postgres:5432
      PYWAY_DATABASE_MIGRATION_DIR: migration
      PYWAY_TABLE: pyway
      PYWAY_TYPE: postgres
      PYWAY_DATABASE_HOST: login-postgres
      PYWAY_DATABASE_PORT: 5432
      PYWAY_DATABASE_NAME: login
      PYWAY_DATABASE_USERNAME: login
      PYWAY_DATABASE_PASSWORD: login
    networks:
      - mle
    depends_on:
      login-postgres:
        condition: service_healthy

  login-postgres:
    image: postgres:17-alpine
    environment:
      POSTGRES_USER: login
      POSTGRES_PASSWORD: login
      POSTGRES_DB: login
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "login"]
      interval: 5s
      retries: 5
    restart: always
    networks:
      - mle

volumes:
  pgdata:

networks:
  mle:
    name: mle
    external: true
