# utiliser python slim image
FROM python:slim

# Définir le répertoire de travail dans le conteneur
WORKDIR /app

# Copier le fichier requirements file dans le conteneur
COPY requirements.txt /app/requirements.txt


# Installer tous les packages nécessaires spécifiés dans requirements.txt
RUN pip install --no-cache-dir -r requirements.txt
RUN pip install scikit-learn==1.3.2
# Copier le reste du contenu du répertoire de travail dans le conteneur
COPY src/app /app

# Copier le fichier modèle dans le conteneur
COPY models/model_rf_clf.pkl /app/model_rf_clf.pkl

# Rendre le port 8000 disponible
EXPOSE 8000

# Exécuter le serveur uvicorn au lancement du conteneur
CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]