name: Build , Test and Push images

on:
  push:
    branches:
      - feature/monitoring/model
  pull_request:
    branches:
      - master

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}
      
      # ---------- BUILD IMAGES -----------------------------------------------
      - name: Build IMPORT DATA
        uses: docker/build-push-action@v5
        with:
          file: src/data/import_data.Dockerfile
          load: true
          tags: alexandrewinger/shield:import_data
      
      - name: Build MAKE DATASET
        uses: docker/build-push-action@v5
        with:
          file: src/data/make_dataset.Dockerfile
          load: true
          tags: alexandrewinger/shield:make_dataset
      
      - name: Build CREATE USERS DB
        uses: docker/build-push-action@v5
        with:
          file: src/users_db/create_users_db.Dockerfile
          load: true
          tags: alexandrewinger/shield:create_users_db

      - name: Build TRAIN MODEL
        uses: docker/build-push-action@v5
        with:
          file: src/models/model.Dockerfile
          load: true
          tags: alexandrewinger/shield:train_model

      - name: Build API
        uses: docker/build-push-action@v5
        with:
          file: src/api/api.Dockerfile
          load: true
          tags: alexandrewinger/shield:api

      - name: Build TEST SHIELD
        uses: docker/build-push-action@v5
        with:
          file: src/test/test_shield.Dockerfile
          load: true
          tags: alexandrewinger/shield:test_shield
      
      # ---------- TEST -------------------------------------------------------
      - name: Run tests
        run: docker compose up --detach

      # ---------- PUSH -------------------------------------------------------
      - name: Build and push IMPORT DATA
        uses: docker/build-push-action@v5
        with:
          file: src/data/import_data.Dockerfile
          push: true
          tags: alexandrewinger/shield:import_data
      
      - name: Build and push MAKE DATASET
        uses: docker/build-push-action@v5
        with:
          file: src/data/make_dataset.Dockerfile
          push: true
          tags: alexandrewinger/shield:make_dataset
      
      - name: Build and push CREATE USERS DB
        uses: docker/build-push-action@v5
        with:
          file: src/users_db/create_users_db.Dockerfile
          push: true
          tags: alexandrewinger/shield:create_users_db

      - name: Build and push TRAIN MODEL
        uses: docker/build-push-action@v5
        with:
          file: src/models/model.Dockerfile
          push: true
          tags: alexandrewinger/shield:train_model

      - name: Build and push API
        uses: docker/build-push-action@v5
        with:
          file: src/api/api.Dockerfile
          push: true
          tags: alexandrewinger/shield:api

      - name: Build and push TEST SHIELD
        uses: docker/build-push-action@v5
        with:
          file: src/test/test_shield.Dockerfile
          push: true
          tags: alexandrewinger/shield:test_shield
