name: PR merged to master

on:
    pull_request:
        types:
        - closed
env:
  DOCKER_HUB_PASS: dckr_pat_c7z819p35OfFdnkGt19m0nd4clM
  
permissions:
  contents: read

jobs:
    if_merged:
      if: github.event.pull_request.merged == true
      runs-on: ubuntu-latest
      steps:
      - name: BuildAndPushDockerImages
        run: |
          echo The PR was merged
  