name: Build and deploy Docker images to Hub on new Tag creation

on:
  push:
    tags:
      - 'v*.*.*'
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set env
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV

      - name: Test
        run: |
          echo $RELEASE_VERSION
          echo ${{ env.RELEASE_VERSION }}

      - name: Login to the Docker Hub
        uses: docker/login-action@v1
        with:
          username: roadaccidentsmlops24
          password: ${{ secrets.DOCKER_HUB_PASS }}
  
      - name: Build and push the model_api Docker image to the roadaccidentsmlops24 DockerHub
        uses: docker/build-push-action@v2
        with:
          context: ./python-packages/model_api/
          push: true
          tags: roadaccidentsmlops24/model_api:latest, roadaccidentsmlops24/model_api:${{ github.run_number }}
          dockerfile: ./python-packages/model_api/Dockerfile
